In [48]:
import numpy as np

### Ridge Regression

The closed form equation for Ridge regression is given by:

$\hat\theta = (X^TX + \alpha A)^{-1}X^Ty$

In [49]:
X=2*np.random.rand(100,1)
y=4+3*X+np.random.rand(100,1)

In [50]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import SGDRegressor

In [51]:
ridge_reg = Ridge(alpha=1, solver='cholesky')
ridge_reg.fit(X,y)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='cholesky', tol=0.001)

In [52]:
ridge_reg.predict([[1.5]])

array([[8.87406522]])

#### Using Stochastic Gradient

In [53]:
sgd_reg= SGDRegressor(penalty='l2')
sgd_reg.fit(X, y.ravel())
sgd_reg.predict([[1.5]])

array([9.07114625])

### Lasso Regression

In [54]:
from sklearn.linear_model import Lasso

In [55]:
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X, y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [56]:
lasso_reg.predict([[1.5]])

array([8.73879845])

### Elastic Net

$j(\theta) = MSE(\theta) + r\alpha\sum_{i=1}^n|\theta_i| + \frac{1-r}{2}\alpha\sum_{i=1}^n \theta_i^2$

In [57]:
from sklearn.linear_model import ElasticNet

In [58]:
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic_net.fit(X,y)

ElasticNet(alpha=0.1, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [59]:
elastic_net.predict([[1.5]])

array([8.61312854])

### Early Stopping

In [63]:
from sklearn.base import clone
from sklearn.pipeline import Pipeline

In [64]:
# prepare the data
poly_scaler = Pipeline([
    ('poly_features',PolynomialFeatures(degree=10, include_bias=False)),
    ('std_scaler', StanderScaler())
])

NameError: name 'PolynomialFeatures' is not defined

In [65]:
X_train_poly_scaled = poly_scaler.fit_transform(X_train)
X_val_poly_scaled = poly_scaler.transform(X_val)

NameError: name 'poly_scaler' is not defined

In [66]:
sgd_reg = SGDRegressor(max_iter=1, tol=-np.infty, warm_start=True,
penalty=None, learning_rate="constant", eta0=0.0005)

In [67]:
minimum_val_error = float("inf")
best_epoch = None
best_model = None
for epoch in range(1000):
    sgd_reg.fit(X_train_poly_scaled, y_train) # continues where it left off
    y_val_predict = sgd_reg.predict(X_val_poly_scaled)
    val_error = mean_squared_error(y_val, y_val_predict)
    if val_error < minimum_val_error:
        minimum_val_error = val_error
best_epoch = epoch
best_model = clone(sgd_reg)

IndentationError: expected an indented block (<ipython-input-67-e6eef6623932>, line 5)